workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-s3-cache

branches:
  - feature/break_tar_limit
  - master

pipeline:
  deps:
    image: golang:1.11
    pull: true
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - dep status

  test:
    image: golang:1.11
    pull: true
    commands:
      - go vet ./...
      - go test -cover ./...

  build_linux_amd64:
    when:
      event: push
      branch: master
    image: golang:1.11
    pull: true
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - |
        if test "${DRONE_TAG}" = ""; then
          go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/drone-s3-cache
        else
          go build -v -ldflags "-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/drone-s3-cache
        fi

  publish_linux_amd64:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: zywillc/drone-s3-cache
    dockerfile: Dockerfile
    tags:
      - git-${DRONE_COMMIT_SHA:0:7}
      - latest
    when:
      event: [ push, tag ]
      branch: master

  slack_notify:
    image: plugins/slack
    channel: dw-drone-build
    secrets: [ slack_webhook ]
    username: drone
    image_url: https://privacy.com.ph/site/wp-content/uploads/2017/04/pass.jpg
    icon_emoji: ":drone:"
    template: "REPO:{{repo.name}}   BUILD:{{build.number}}\n BRANCH:{{build.branch}}   COMMIT:{{truncate build.commit 8}}\n MESSAGE:{{build.message}}\n TRIGGERED by {{build.author}}   Succeeded."
    when:
      status: [ success, changed ]
      event: push

  slack_notify:
    image: plugins/slack
    channel: dw-drone-build
    secrets: [ slack_webhook ]
    username: drone
    image_url: http://eightball.ie/wp-content/uploads/sites/377/2016/05/FAIL.png
    icon_emoji: ":drone:"
    template: "REPO:{{repo.name}}   BUILD:{{build.number}}\n BRANCH:{{build.branch}}   COMMIT:{{truncate build.commit 8}}\n MESSAGE:{{build.message}}\n TRIGGERED by {{build.author}}   Failed.\n Please fix it."
    when:
      status: failure
      event: push
